packages:
  - packages/*
  - meta/*

catalog:
  '@eslint/compat': ^2.0.3
  eslint: ^10.0.3
  ts-morph: ^27.0.2
  typescript: ^5.8.2
  typescript-eslint: ^8.57.1
  vitest: ^4.1.0

onlyBuiltDependencies:
  - '@playwright/browser-chromium'
  - esbuild
