export {getFirstAndLast} from './getFirstAndLast';
export {inclusiveRange} from './inclusiveRange';
export {makeBiPermutations} from './makeBiPermutations';
export {pluckKey} from './pluckKey';
export {pluckValue} from './pluckValue';
export {sortValueAscKeyAsc} from './sortValueAscKeyAsc';
export {sortValueAscKeyDesc} from './sortValueAscKeyDesc';
export {sortValueDescKeyAsc} from './sortValueDescKeyAsc';
export {sortValueDescKeyDesc} from './sortValueDescKeyDesc';
